(function(){
  "use strict";
  var topbar=document.getElementById("topbar"),hamburger=document.getElementById("hamburger"),mobileMenu=document.getElementById("mobileMenu"),progress=document.getElementById("pageProgress"),backTop=document.getElementById("backTop"),glow=document.getElementById("cursorGlow"),year=document.getElementById("year");
  if(year){year.textContent=new Date().getFullYear();}
  function updateHeader(){
    if(topbar){topbar.classList.toggle("scrolled",window.scrollY>16);}var max=document.documentElement.scrollHeight-window.innerHeight;var pct=max>0?(window.scrollY/max)*100:0;if(progress){progress.style.width=pct+"%";}if(backTop){backTop.classList.toggle("show",window.scrollY>700);}
  }
  updateHeader();window.addEventListener("scroll",updateHeader,{passive:true});window.addEventListener("resize",updateHeader);
  function closeMobileMenu(){if(!mobileMenu||!hamburger)return;mobileMenu.classList.remove("show");hamburger.classList.remove("open");hamburger.setAttribute("aria-expanded","false");document.body.classList.remove("menu-open");}
  if(hamburger&&mobileMenu){hamburger.addEventListener("click",function(){var open=mobileMenu.classList.toggle("show");hamburger.classList.toggle("open",open);hamburger.setAttribute("aria-expanded",String(open));document.body.classList.toggle("menu-open",open);});mobileMenu.querySelectorAll("a").forEach(function(link){link.addEventListener("click",closeMobileMenu);});}
  if(backTop){backTop.addEventListener("click",function(){window.scrollTo({top:0,behavior:"smooth"});});}
  document.addEventListener("keydown",function(e){if(e.key==="Escape"){closeMobileMenu();closeDrawer();}});
  if(glow&&window.matchMedia("(pointer:fine)").matches){document.addEventListener("pointermove",function(e){glow.style.left=e.clientX+"px";glow.style.top=e.clientY+"px";},{passive:true});}
  var words=["Online Presence","Client Trust","Lead Generation","Booking Conversion","Custom Software","Client Portals","Payment Flows","Delivery Tracking","Website Credibility","Marketing ROI"];var word=document.getElementById("rotatingWord"),wordIndex=0;if(word){setInterval(function(){wordIndex=(wordIndex+1)%words.length;word.style.opacity="0";word.style.transform="translateY(6px)";setTimeout(function(){word.textContent=words[wordIndex];word.style.opacity="1";word.style.transform="translateY(0)";},180);},1900);}
  var reveals=document.querySelectorAll(".reveal");if("IntersectionObserver"in window){var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target);}});},{threshold:.12});reveals.forEach(function(el){observer.observe(el);});}else{reveals.forEach(function(el){el.classList.add("is-visible");});}
  var navLinks=Array.prototype.slice.call(document.querySelectorAll(".menu a,.mobile-menu a"));function currentPageName(){var path=window.location.pathname.split("/").pop();return path===""?"index.html":path;}function updateActiveNav(){var current=currentPageName();navLinks.forEach(function(link){var href=(link.getAttribute("href")||"").split("#")[0].split("?")[0];link.classList.toggle("active",href===current);});}
  updateActiveNav();
  var serviceData={presence:{tag:"Managed presence",title:"Fully Managed Digital Presence",text:"A branded website with hosting guidance, updates, SEO basics, analytics, and support, so the business can focus on clients.",list:["Branded website pages","Hosting and security guidance","Monthly content updates"]},software:{tag:"Custom software",title:"Custom Software Development",text:"Business software built around the exact workflow you need, including client portals, booking systems, payment platforms, delivery tracking apps, and dashboards.",list:["Client portals and logins","Booking and payment systems","Delivery tracking and admin dashboards"]},systems:{tag:"Systems and performance",title:"Systems Development & Performance",text:"Digital workflows that help visitors become enquiries through forms, quote paths, booking journeys, tracking, automation ideas, and performance dashboards.",list:["Lead capture forms","Quote and booking flows","Analytics and conversion tracking"]},brand:{tag:"Brand growth",title:"Brand Strategy & Growth Operations",text:"Brand messaging, conversion copy, social content direction, and KPI reporting to make the online presence clearer and more trustworthy.",list:["Visual identity direction","Conversion copywriting","Social campaign structure"]}};
  var serviceCards=document.querySelectorAll(".service-card"),previewTag=document.getElementById("previewTag"),previewTitle=document.getElementById("previewTitle"),previewText=document.getElementById("previewText"),previewList=document.getElementById("previewList");function setService(type){var item=serviceData[type]||serviceData.presence;serviceCards.forEach(function(card){card.classList.toggle("active",card.getAttribute("data-service")===type);});if(previewTag)previewTag.textContent=item.tag;if(previewTitle)previewTitle.textContent=item.title;if(previewText)previewText.textContent=item.text;if(previewList){previewList.innerHTML="";item.list.forEach(function(text){var li=document.createElement("li");li.textContent=text;previewList.appendChild(li);});}}
  serviceCards.forEach(function(card){card.addEventListener("click",function(){setService(card.getAttribute("data-service"));});card.addEventListener("keydown",function(e){if(e.key===" "){e.preventDefault();setService(card.getAttribute("data-service"));}else if(e.key==="Enter"){setService(card.getAttribute("data-service"));}});});if(serviceCards.length){setService("presence");}
  var packageData={starter:{label:"Website Launch selected",title:"Start with a clean professional website.",text:"Best for businesses that need a simple online presence and a clear way for clients to contact them.",subject:"Website Launch Enquiry"},growth:{label:"Growth Presence selected",title:"Build a stronger online presence.",text:"Best for businesses that want a website, content support, SEO basics, analytics, and more trust-building sections.",subject:"Growth Presence Enquiry"},software:{label:"Custom Software Build selected",title:"Build a client portal, booking system, payment platform, delivery tracking app, or dashboard.",text:"Best for businesses that need custom tools such as secure client portals, booking calendars, payment flows, delivery tracking apps, or admin dashboards.",subject:"Custom Software Development Enquiry"},engine:{label:"Digital Growth Engine selected",title:"Connect website, software, social media, and systems.",text:"Best for businesses that want lead capture, campaigns, quote or booking flows, software workflows, and a complete digital system.",subject:"Digital Growth Engine Enquiry"}};
  var packageCards=document.querySelectorAll(".package-card"),packageLabel=document.getElementById("packageLabel"),packageTitle=document.getElementById("packageTitle"),packageText=document.getElementById("packageText"),packageEmail=document.getElementById("packageEmail");function enquiryHref(subject,title){var body="Hi NemaSites,\n\nI am interested in: "+title+"\n\nBusiness name:\nIndustry:\nServices offered:\nWebsite/software/system needed:\nFeatures needed, for example client portal, booking system, payment platform, delivery tracking app, or dashboard:\nTimeline:\n\nPlease send me a quote and recommended structure.";return"mailto:info@nemasites.com?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(body);}function setPackage(type){var item=packageData[type]||packageData.starter;packageCards.forEach(function(card){card.classList.toggle("is-selected",card.getAttribute("data-package")===type);});if(packageLabel)packageLabel.textContent=item.label;if(packageTitle)packageTitle.textContent=item.title;if(packageText)packageText.textContent=item.text;if(packageEmail)packageEmail.href=enquiryHref(item.subject,item.title);}
  packageCards.forEach(function(card){card.addEventListener("click",function(e){if(e.target&&e.target.tagName==="A")return;setPackage(card.getAttribute("data-package"));});card.addEventListener("keydown",function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();setPackage(card.getAttribute("data-package"));}});});if(packageCards.length){setPackage("starter");}
  var statsGrid=document.getElementById("statsGrid"),counted=false;function animateStats(){if(counted)return;counted=true;document.querySelectorAll("[data-count]").forEach(function(el){var target=parseInt(el.getAttribute("data-count"),10)||0;var current=0;var step=Math.max(1,Math.ceil(target/40));var timer=setInterval(function(){current+=step;if(current>=target){current=target;clearInterval(timer);}el.textContent=String(current);},24);});}
  if(statsGrid&&"IntersectionObserver"in window){var statObserver=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){animateStats();statObserver.disconnect();}});},{threshold:.25});statObserver.observe(statsGrid);}else{animateStats();}
  var contactForm=document.getElementById("contactForm");if(contactForm){contactForm.addEventListener("submit",function(e){e.preventDefault();var name=document.getElementById("name").value.trim();var contactDetail=document.getElementById("contactDetail").value.trim();var type=document.getElementById("type").value;var message=document.getElementById("message").value.trim();var subject="NemaSites Project Enquiry - "+type;var body="Hi NemaSites,\n\nMy name is "+name+".\n\nContact detail: "+(contactDetail||"Not provided")+"\nProject type: "+type+"\n\nMessage:\n"+message+"\n\nPlease contact me with the next steps.";window.location.href="mailto:info@nemasites.com?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(body);});}
  var quoteToggle=document.getElementById("quoteToggle"),quoteDrawer=document.getElementById("quoteDrawer"),quoteClose=document.getElementById("quoteClose"),drawerEmail=document.getElementById("drawerEmail"),drawerButtons=document.querySelectorAll("[data-drawer]");var drawerData={website:"Website Project Enquiry",software:"Custom Software Development Enquiry",portal:"Client Portal Enquiry",booking:"Booking System Enquiry",payment:"Payment Platform Enquiry",tracking:"Delivery Tracking App Enquiry",social:"Social Media Marketing Enquiry",all:"4-in-1 Digital Growth Package Enquiry"};function closeDrawer(){if(quoteDrawer){quoteDrawer.classList.remove("open");quoteDrawer.setAttribute("aria-hidden","true");}}function openDrawer(){if(quoteDrawer){quoteDrawer.classList.add("open");quoteDrawer.setAttribute("aria-hidden","false");}}
  if(quoteToggle){quoteToggle.addEventListener("click",function(){if(quoteDrawer&&quoteDrawer.classList.contains("open")){closeDrawer();}else{openDrawer();}});}if(quoteClose){quoteClose.addEventListener("click",closeDrawer);}drawerButtons.forEach(function(button){button.addEventListener("click",function(){var type=button.getAttribute("data-drawer");var subject=drawerData[type]||drawerData.website;drawerButtons.forEach(function(btn){btn.classList.remove("active");});button.classList.add("active");if(drawerEmail){var body="Hi NemaSites,\n\nI want to enquire about: "+subject+"\n\nBusiness name:\nIndustry:\nGoal:\nFeatures needed, for example client portal, booking system, payment platform, delivery tracking app, or dashboard:\nTimeline:\n\nPlease send me more information and a quote.";drawerEmail.href="mailto:info@nemasites.com?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(body);}});});

  var projectSlider=document.querySelector(".project-slider");
  if(projectSlider){
    var autoTimer=null,resumeTimer=null;
    function step(){
      if(!projectSlider)return;
      var card=projectSlider.querySelector(".project-card");
      var gap=card?parseFloat(getComputedStyle(projectSlider).columnGap||18):18;
      var advance=(card?card.getBoundingClientRect().width:280)+gap;
      var atEnd=projectSlider.scrollLeft+projectSlider.clientWidth>=projectSlider.scrollWidth-4;
      projectSlider.scrollTo({left:atEnd?0:projectSlider.scrollLeft+advance,behavior:"smooth"});
    }
    function startAuto(){stopAuto();autoTimer=setInterval(step,3200);}
    function stopAuto(){if(autoTimer){clearInterval(autoTimer);autoTimer=null;}}
    function pauseThenResume(){stopAuto();if(resumeTimer)clearTimeout(resumeTimer);resumeTimer=setTimeout(startAuto,5000);}
    ["pointerdown","touchstart","wheel"].forEach(function(evt){projectSlider.addEventListener(evt,pauseThenResume,{passive:true});});
    if(!(window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches)){startAuto();}
  }
})();
